version: "3.8"

services:
  #db
  db:
    image: postgres:14-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  #api
  api:
    build: .
    container_name: "comments-api"
    environment:
      DB_USERNAME: "postgres"
      DB_USER: "postgres"
      DB_NAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    networks:
      - fullstack
    depends_on:
      - db

volumes:
  database_postgres:
networks:
    fullstack:
      driver: bridge

